/* This SAS program was automatically generated by Stat/Transfer */

/* The following line should contain the complete path and name of your raw data file */
FILENAME datafile '.\toimenpideluokitus 2009.dat' ;

/* The following line should contain the directory in which you wish your SAS file to be stored */
libname library '.' ;

/* The following line contains the name (without the extension) for your SAS dataset */
%LET dataset = toimenpi ;

DATA library.&dataset ;
INFILE datafile LRECL=2194;
INPUT
   C1 $ 1-8                 C2 $ 9-58                C3 $ 59-108           
   C4 $ 109-251             C5 $ 252-263             C6 $ 264-276          
   C7 $ 277-293             C8 $ 294-312             C9 $ 313-322          
   C10 $ 323-342            C11 $ 343-346            C12 $ 347-453         
   C13 $ 454-456            C14 $ 457-710            C15 $ 711-820         
   C16 $ 821-1074           C17 $ 1075-1269          C18 $ 1270-1283       
   C19 $ 1284-1293          C20 $ 1294-1487          C21 $ 1488-1665       
   C22 $ 1666-1874          C23 $ 1875-1880          C24 $ 1881-1889       
   C25 $ 1890-1897          C26 $ 1898-1907          C27 $ 1908-1916       
   C28 $ 1917-1927          C29 $ 1928-1937          C30 $ 1938-2108       
   C31 $ 2109-2112          C32 $ 2113-2155          C33 $ 2156-2173       
   C34 $ 2174-2177          C35 $ 2178-2186          C36 $ 2187-2194 ;     

RUN ;
