procedure spettran
select ncsp_koo
set filter to not released
goto top
set printer off
lc_first=' '
do while not eof()
  if code <> lc_first
    lc_first=substr(code,1,1)
    lc_print='\data\ncsp\suomi\spet_'+lc_first+'.txt'
    set printer off
    set printer to (lc_print)
    set printer on
    set console off
    ? ';;Date:   1997-12-18'
    ? ';;Author: marttiv@stakes.fi'
    ? ';;Generated by: Spet'
    ? 'AUTHOR "marttiv@stakes.fi"'
    ?
  endif
  ? 'STATUS "0"'
  ? 'HISTORY "19971218,marttiv@stakes.fi,0;"'
  ? 'RUBRIC "'+ trim(text)+'"'
  ? 'ENGLISH_RUBRIC "'+trim(english)+'"'
  ? 'SOURCE "NCSP-FI" CODE "'+code+'"'
  ? 'MAIN '
  ?
  ?
  select ncsp_koo
  skip
enddo
set printer off
set printer to
set console on
return